wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/mtl_trex_baseColor.jpg"
wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/mtl_trex_emissive.jpg"
wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/mtl_trex_metallicRoughness.jpg"
wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/trex_nml.png"
wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/trex_running.bin"
wget -nc -P trex "https://raw.githubusercontent.com/BabylonJS/Exporters/master/Maya/Samples/glTF%%202.0/T-Rex/trex_running.gltf"
